package com.guanyi.tools;

import java.util.ArrayList;

public class Constant
{
  public static final String ADD_ADDRESS = "";
  public static final String APPKEY = "appkey";
  public static final String APPKEYVALUE = "*#ml_ANDROID_ytnmct_36_0307&*";
  public static final String APPVERSION = "appversion";
  public static final String APPVERVALUE = "2.1.0";
  public static final String AUTHTYPEVALUE = "md5";
  public static final int BAOYE = 6;
  public static final String CANAL = "官网";
  public static final String CARRIER = "carrier";
  public static final String CASH = "cash";
  public static final String CHANELID = "1";
  public static final int CLAFIELD = 7;
  public static final String CLASS = "class";
  public static final String CLEAR_BUFF_FLAG = "clearBuffFlag";
  public static final String CLIENT_V = "client_v";
  public static final String CN_OPERATOR = "cn_operator";
  public static final String CONTENT_TYPE = "content_type";
  public static final int DATA_IS_ERROR = 11;
  public static final int DATA_IS_NULL = 4;
  public static final int DATA_IS_SUCCESS = 5;
  public static final int DELETE_DATA_SUCCESS = 10;
  public static final String DEVICENAME = "devicename";
  public static final int DIALOG_ID_DOWNLOADING = 100;
  public static final int DIALOG_ID_GET_LOGGEDIN_USER = 105;
  public static final int DIALOG_ID_SEND_NEWSFEED = 106;
  public static final String FAILURE = "failure";
  public static final String GOODSDESCRIPTION = "goodsdescription";
  public static final String HTTPHEAD = "httphead";
  public static final String HTTPHEADER = "Httpheader";
  public static final String IMEI = "imei";
  public static final String IMSI = "imsi";
  public static final int ING2ING = 5;
  public static final String ISFIRST = "isfirst";
  public static final String LANGUAGE = "language";
  public static final int LOGIN_SUCESS = 1234;
  public static final String LQBAL = "lqbal";
  public static final String MEMBERTYPE = "membertype";
  public static final String MESID = "mesid";
  public static final String MODEL = "model";
  public static final int MONTEAMOR = 9;
  public static final int MOONBASA_BAR = 2;
  public static final int MOONBASA_GRIL = 1;
  public static final int MOONBASA_SHOE = 10;
  public static final int MORE_ID = 1;
  public static final int MSG_NETWORK_FAIL = 7;
  public static final int MSG_NETWORK_FAILURE = 8;
  public static final int MSG_NETWORK_NO_ACCESS = 2;
  public static final int MSG_NETWORK_OK = 3;
  public static final String NAME = "name";
  public static final String OS = "os";
  public static final String OSVALUE = "android";
  public static final String OSVERSION = "osversion";
  public static final String PLATFORM_N = "platform_n";
  public static final String POINT = "point";
  public static final int PUSH_LOOP_TIME = 3600000;
  public static final int QIANJIN = 8;
  public static final int RESULT_CLASS_CAST_ERR = -5;
  public static final int RESULT_FAILED = 0;
  public static final int RESULT_FAILED_ARG_ERR = -2;
  public static final int RESULT_FAILED_ENCODER_ERR = -6;
  public static final int RESULT_FAILED_JSON_PARSE_ERR = -3;
  public static final int RESULT_FAILED_MALFORMEDURL_ERR = -4;
  public static final int RESULT_FAILED_NETWORK_ERR = -1;
  public static final int RESULT_FAILED_REQUEST_ERR = -7;
  public static final int RESULT_GET_FRIENDS_OK = 2;
  public static final int RESULT_GET_USERINFO_OK = 3;
  public static final int RESULT_OK = 1;
  public static final int RESULT_POST_ADDRECORD_OK = 4;
  public static final int RUTISHER = 3;
  public static final int SCOLL_IS_END = 9;
  public static final String SCREEN_SIZE = "screen_size";
  public static String SERVICEPGN;
  public static String SERVICEPGNNAME;
  public static final String SESSIONID = "sessoinid";
  public static final String SHOPCARTNUM = "shopcartnum";
  public static final String SIGN = "sign";
  public static final String SMS_CENTER_NUMBER = "sms_center_number";
  public static final String SOURCE = "source";
  public static final String SOURCEID = "sourceid";
  public static String SOURCEIDVALUE;
  public static final String SOURCE_V = "1";
  public static final int SPACETIME = 30;
  public static final String SUCCESS = "success";
  public static final int SUORANG = 4;
  public static final String SYSTETM = "system";
  public static final String TIME = "";
  public static final int TIMEOUT_TIME = 30000;
  public static final String UDID = "udid";
  public static String UDID_VALUE;
  public static final String UID = "uid";
  public static final int UPDATE_ADDRESS_OK = 6;
  public static final String URL = "http://";
  public static final String USER = "user";
  public static final String USERAGENT = "User-Agent";
  public static final String USERID = "userid";
  public static final String USERNAME = "username";
  public static final String VER = "ver";
  public static final String VERVALUE = "1.0";
  public static final String WANTYPE = "wantype";
  public static final String WEBLOGID = "weblogid";
  public static final String WEBLOGIDVALUE = "weblogid";
  public static final String WEBSITEID = "website_id";
  public static String YOUHUI = "";
  public static final String appkey = "2574658669";
  public static final String appsecret = "96ac2709d4b8345c6c0d0bcc9b5db58c";
  public static float density = 0.0F;
  public static int height = 0;
  public static final ArrayList<String> messageList;
  public static final String sinaweibo = "sina_weibo_data";
  public static int width;

  static
  {
    SOURCEIDVALUE = "1111111";
    UDID_VALUE = "";
    SERVICEPGN = "";
    SERVICEPGNNAME = "SERVICEPGNNAME";
    messageList = new ArrayList();
    density = 0.0F;
  }
}
